# Generated by Django 4.2.9 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["tenant", "-created_at"], name="chat_sess_tenant_created_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["session", "created_at"], name="chat_msg_session_created_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["role", "created_at"], name="chat_msg_role_created_idx"),
        ),
    ]
