# Generated by Django 4.2.9 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["tenant", "status"], name="doc_tenant_status_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["tenant", "-created_at"], name="doc_tenant_created_idx"),
        ),
        migrations.AddIndex(
            model_name="documentchunk",
            index=models.Index(fields=["document", "chunk_index"], name="doc_chunk_doc_chunk_idx"),
        ),
    ]
