# Generated by Django 4.2.9 on 2026-03-17 16:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_update_tenant_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel_type', models.CharField(choices=[('web', 'Web Widget'), ('telegram', 'Telegram Bot'), ('whatsapp', 'WhatsApp Business')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('input_mode', models.CharField(choices=[('text', 'Text Only'), ('voice', 'Voice Only'), ('both', 'Text & Voice')], default='both', max_length=10)),
                ('telegram_token', models.CharField(blank=True, max_length=200)),
                ('telegram_webhook_set', models.BooleanField(default=False)),
                ('whatsapp_token', models.CharField(blank=True, max_length=500)),
                ('whatsapp_phone_id', models.CharField(blank=True, max_length=100)),
                ('whatsapp_verify_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_channels',
                'unique_together': {('tenant', 'channel_type')},
            },
        ),
    ]
