# Generated by Django 6.0.2 on 2026-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='tenants/logos/'),
        ),
    ]
