# Generated by Django 4.2.9 on 2026-03-05 09:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('response_time', models.FloatField()),
                ('chunks_used', models.IntegerField(default=0)),
                ('was_answered', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'query_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_queries', models.IntegerField(default=0)),
                ('total_documents', models.IntegerField(default=0)),
                ('indexed_documents', models.IntegerField(default=0)),
                ('active_sessions', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
    ]
